version: '3.8'

services:
  redis:
    restart: unless-stopped
    volumes:
      - ./redis/redis.conf:/app/redis.conf

  server:
    restart: unless-stoped
    volumes:
      - ./server:/app

  nginx:
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/magallanes_nginx.conf:/etc/nginx/conf.d/magallanes_nginx.conf
