---
swagger: '2.0'
info:
  version: 0.0.1
  title: '@Beria server API doc list'
  description: |
    @Apple_pie second part API
    last update: 02/02/2021 13:23
    все API сервера начинаются с /api роута
tags:
- name: geolocation
  description: Список городов
paths:
  '/city/:country':
    post:
      tags:
      - geolocation
      summary: регистрация через email
      parameters:
      - name: sub
        in: query
        description: подстрока (для фильтрации городов)
        required: false
        type: string
      responses:
        '200':
          description: список городов
          schema:
            type: array
            items:
              '$ref': '#/definitions/City'
        '406':
          description: Неверная страна

definitions:
  City:
    type: object
    properties:
      id:
        type: string
        description: id города
        required: true
      title:
        type: object
        required: true
        properties:
          origin:
            type: string
            description: название города на родном языке
            required: true
          en:
            type: string
            required: true
            description: название города на english
