name: Deploy Swagger API to test server

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch test branch
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: root
          password: ${{ secrets.TEST_SERVER_SSH_PASSWORD }}
          script: |
            cd /Magellanes
            git reset --hard HEAD
            git pull origin master
